name: sql_conn

description: >
  Universal production-ready Flutter SQL connector using JDBC and secure pooled connections.

version: 2.0.0
homepage: https://github.com/VaishnavDatir/sql_conn
repository: https://github.com/VaishnavDatir/sql_conn
issue_tracker: https://github.com/VaishnavDatir/sql_conn/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^26.1.7
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: plugin.sqlconn.sql_conn
        pluginClass: SqlConnPlugin
